<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE calendar [

<!ELEMENT calendar (year)>
<!ATTLIST calendar
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED>
<!ELEMENT year (month)+>
<!ATTLIST year
  xmlns CDATA #FIXED ''
  ordinal CDATA #REQUIRED>
<!ELEMENT month (week)+>
<!ATTLIST month
  xmlns CDATA #FIXED ''
  name NMTOKEN #REQUIRED
  ordinal CDATA #REQUIRED>
<!ELEMENT week (day)+>
<!ATTLIST week
  xmlns CDATA #FIXED ''
  ordinal CDATA #REQUIRED>
<!ELEMENT day (job)?>
<!ATTLIST day
  xmlns CDATA #FIXED ''
  date CDATA #REQUIRED
  name NMTOKEN #REQUIRED
  ordinal CDATA #REQUIRED>
<!ELEMENT job EMPTY>
<!ATTLIST job
  xmlns CDATA #FIXED ''
  number CDATA #REQUIRED>
<!ENTITY nbsp "&#xA0;">

]>
<calendar id="Custom Sign Center">
	<year ordinal="2017">
		<month ordinal="5" name="May">
			<week ordinal="1">
				<day ordinal="1" name="Sunday" date=""></day>
				<day ordinal="2" name="Monday" date="1">
					<job number="578"></job>
				</day>
				<day ordinal="3" name="Tuesday" date="2"/>
				<day ordinal="4" name="Wednesday" date="3"/>
				<day ordinal="5" name="Thursday" date="4"/>
				<day ordinal="6" name="Friday" date="5"/>
				<day ordinal="7" name="Saturday" date="6"/>
			</week>
			<week ordinal="2">
				<day ordinal="8" name="Sunday" date="7"/>
				<day ordinal="9" name="Monday" date="8"/>
				<day ordinal="10" name="Tuesday" date="9"/>
				<day ordinal="11" name="Wednesday" date="10"></day>
				<day ordinal="12" name="Thursday" date="11"></day>
				<day ordinal="13" name="Friday" date="12"/>
				<day ordinal="14" name="Saturday" date="13"/>
			</week>
			<week ordinal="3">
				<day ordinal="15" name="Sunday" date="14"/>
				<day ordinal="16" name="Monday" date="15"/>
				<day ordinal="17" name="Tuesday" date="16"/>
				<day ordinal="18" name="Wednesday" date="17"/>
				<day ordinal="19" name="Thursday" date="18"></day>
				<day ordinal="20" name="Friday" date="19"></day>
				<day ordinal="21" name="Saturday" date="20"/>
			</week>
			<week ordinal="4">
				<day ordinal="22" name="Sunday" date="21"/>
				<day ordinal="23" name="Monday" date="22"></day>
				<day ordinal="24" name="Tuesday" date="23"></day>
				<day ordinal="25" name="Wednesday" date="24"></day>
				<day ordinal="26" name="Thursday" date="25"></day>
				<day ordinal="27" name="Friday" date="26"></day>
				<day ordinal="28" name="Saturday" date="27"/>
			</week>
			<week ordinal="5">
				<day ordinal="29" name="Sunday" date="28"/>
				<day ordinal="30" name="Monday" date="29"></day>
				<day ordinal="31" name="Tuesday" date="30"></day>
				<day ordinal="32" name="Wednesday" date="31"/>
				<day ordinal="33" name="Thursday" date=""></day>
				<day ordinal="34" name="Friday" date=""></day>
				<day ordinal="35" name="Saturday" date=""></day>
			</week>
		</month>
		<month ordinal="6" name="June">
			<week ordinal="1">
				<day ordinal="1" name="Sunday" date=""></day>
				<day ordinal="2" name="Monday" date=""></day>
				<day ordinal="3" name="Tuesday" date=""></day>
				<day ordinal="4" name="Wednesday" date=""></day>
				<day ordinal="5" name="Thursday" date="1"></day>
				<day ordinal="6" name="Friday" date="2"></day>
				<day ordinal="7" name="Saturday" date="3"/>
			</week>
			<week ordinal="2">
				<day ordinal="8" name="Sunday" date="4"/>
				<day ordinal="9" name="Monday" date="5"></day>
				<day ordinal="10" name="Tuesday" date="6"></day>
				<day ordinal="11" name="Wednesday" date="7"></day>
				<day ordinal="12" name="Thursday" date="8"></day>
				<day ordinal="13" name="Friday" date="9"></day>
				<day ordinal="14" name="Saturday" date="10"/>
			</week>
			<week ordinal="3">
				<day ordinal="15" name="Sunday" date="11"/>
				<day ordinal="16" name="Monday" date="12"></day>
				<day ordinal="17" name="Tuesday" date="13"></day>
				<day ordinal="18" name="Wednesday" date="14"></day>
				<day ordinal="19" name="Thursday" date="15"></day>
				<day ordinal="20" name="Friday" date="16"></day>
				<day ordinal="21" name="Saturday" date="17"/>
			</week>
			<week ordinal="4">
				<day ordinal="22" name="Sunday" date="18"/>
				<day ordinal="23" name="Monday" date="19"></day>
				<day ordinal="24" name="Tuesday" date="20"></day>
				<day ordinal="25" name="Wednesday" date="21"></day>
				<day ordinal="26" name="Thursday" date="22"></day>
				<day ordinal="27" name="Friday" date="23"></day>
				<day ordinal="28" name="Saturday" date="24"/>
			</week>
			<week ordinal="5">
				<day ordinal="29" name="Sunday" date="25"/>
				<day ordinal="30" name="Monday" date="26"></day>
				<day ordinal="31" name="Tuesday" date="27"/>
				<day ordinal="32" name="Wednesday" date="28"/>
				<day ordinal="33" name="Thursday" date="29"/>
				<day ordinal="34" name="Friday" date="30"></day>
				<day ordinal="35" name="Saturday" date=""></day>
			</week>
		</month>
		<month ordinal="7" name="July">
			<week ordinal="1">
				<day ordinal="1" name="Sunday" date=""/>
				<day ordinal="2" name="Monday" date=""/>
				<day ordinal="3" name="Tuesday" date=""/>
				<day ordinal="4" name="Wednesday" date=""/>
				<day ordinal="5" name="Thursday" date=""/>
				<day ordinal="6" name="Friday" date=""/>
				<day ordinal="7" name="Saturday" date="1"></day>
			</week>
			<week ordinal="2">
				<day ordinal="8" name="Sunday" date="2"/>
				<day ordinal="9" name="Monday" date="3"/>
				<day ordinal="10" name="Tuesday" date="4"/>
				<day ordinal="11" name="Wednesday" date="5"></day>
				<day ordinal="12" name="Thursday" date="6"/>
				<day ordinal="13" name="Friday" date="7"></day>
				<day ordinal="14" name="Saturday" date="8"/>
			</week>
			<week ordinal="3">
				<day ordinal="15" name="Sunday" date="9"></day>
				<day ordinal="16" name="Monday" date="10"></day>
				<day ordinal="17" name="Tuesday" date="11"></day>
				<day ordinal="18" name="Wednesday" date="12"/>
				<day ordinal="19" name="Thursday" date="13"/>
				<day ordinal="20" name="Friday" date="14"></day>				
				<day ordinal="21" name="Saturday" date="15"/>
			</week>
			<week ordinal="4">
				<day ordinal="22" name="Sunday" date="16"/>
				<day ordinal="23" name="Monday" date="17"></day>
				<day ordinal="24" name="Tuesday" date="18"/>
				<day ordinal="25" name="Wednesday" date="19"/>
				<day ordinal="26" name="Thursday" date="20"/>
				<day ordinal="27" name="Friday" date="21"></day>
				<day ordinal="28" name="Saturday" date="22"/>
			</week>
			<week ordinal="5">
				<day ordinal="29" name="Sunday" date="23"/>
				<day ordinal="30" name="Monday" date="24"/>
				<day ordinal="31" name="Tuesday" date="25"/>
				<day ordinal="32" name="Wednesday" date="26"/>
				<day ordinal="33" name="Thursday" date="27"/>
				<day ordinal="34" name="Friday" date="28"></day>
				<day ordinal="35" name="Saturday" date="29"/>
			</week>
			<week ordinal="6">
				<day ordinal="36" name="Sunday" date="30"/>
				<day ordinal="37" name="Monday" date="31"/>
				<day ordinal="38" name="Tuesday" date=""/>
				<day ordinal="39" name="Wednesday" date=""/>
				<day ordinal="40" name="Thursday" date=""/>
				<day ordinal="41" name="Friday" date=""/>
				<day ordinal="42" name="Saturday" date=""/>
			</week>
		</month>
	</year>
</calendar>